version: '3.9'

services:
  lunarcore:
    container_name: lunarcore
    build:
      context: .
      tags:
        - lunarcore:latest
        - lunarcore:${LUNARCORE_VERSION}
    tty: true
    volumes:
      - ./downloads/StarRailData:/app/resources
      - ./data/data:/app/data
      - type: bind
        source: ./data/ssl/keystore.p12
        target: /app/keystore.p12
      - type: bind
        source: ./data/config.json
        target: /app/config.json
    ports:
      - 4443:443
      - 23301:23301
